// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: audio_streaming.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_audio_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_audio_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_audio_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_audio_streaming_proto protoreflect.FileDescriptor

const file_audio_streaming_proto_rawDesc = "" +
	"\n" +
	"\x15audio_streaming.proto\x12\tservicios\"*\n" +
	"\rStreamRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\" \n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2T\n" +
	"\x10StreamingService\x12@\n" +
	"\vStreamAudio\x12\x18.servicios.StreamRequest\x1a\x15.servicios.AudioChunk0\x01B\tZ\a/protosb\x06proto3"

var (
	file_audio_streaming_proto_rawDescOnce sync.Once
	file_audio_streaming_proto_rawDescData []byte
)

func file_audio_streaming_proto_rawDescGZIP() []byte {
	file_audio_streaming_proto_rawDescOnce.Do(func() {
		file_audio_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_streaming_proto_rawDesc), len(file_audio_streaming_proto_rawDesc)))
	})
	return file_audio_streaming_proto_rawDescData
}

var file_audio_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_audio_streaming_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: servicios.StreamRequest
	(*AudioChunk)(nil),    // 1: servicios.AudioChunk
}
var file_audio_streaming_proto_depIdxs = []int32{
	0, // 0: servicios.StreamingService.StreamAudio:input_type -> servicios.StreamRequest
	1, // 1: servicios.StreamingService.StreamAudio:output_type -> servicios.AudioChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audio_streaming_proto_init() }
func file_audio_streaming_proto_init() {
	if File_audio_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_streaming_proto_rawDesc), len(file_audio_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_streaming_proto_goTypes,
		DependencyIndexes: file_audio_streaming_proto_depIdxs,
		MessageInfos:      file_audio_streaming_proto_msgTypes,
	}.Build()
	File_audio_streaming_proto = out.File
	file_audio_streaming_proto_goTypes = nil
	file_audio_streaming_proto_depIdxs = nil
}
