// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: streaming.proto

package serviciosStreaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SolicitudStreaming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RutaArchivo   string                 `protobuf:"bytes,1,opt,name=rutaArchivo,proto3" json:"rutaArchivo,omitempty"` // ruta del archivo mp3 en el servidor de streaming
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudStreaming) Reset() {
	*x = SolicitudStreaming{}
	mi := &file_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudStreaming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudStreaming) ProtoMessage() {}

func (x *SolicitudStreaming) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudStreaming.ProtoReflect.Descriptor instead.
func (*SolicitudStreaming) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudStreaming) GetRutaArchivo() string {
	if x != nil {
		return x.RutaArchivo
	}
	return ""
}

type FragmentoAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datos         []byte                 `protobuf:"bytes,1,opt,name=datos,proto3" json:"datos,omitempty"` // fragmento binario del mp3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FragmentoAudio) Reset() {
	*x = FragmentoAudio{}
	mi := &file_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentoAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentoAudio) ProtoMessage() {}

func (x *FragmentoAudio) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentoAudio.ProtoReflect.Descriptor instead.
func (*FragmentoAudio) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *FragmentoAudio) GetDatos() []byte {
	if x != nil {
		return x.Datos
	}
	return nil
}

var File_streaming_proto protoreflect.FileDescriptor

const file_streaming_proto_rawDesc = "" +
	"\n" +
	"\x0fstreaming.proto\x12\tstreaming\"6\n" +
	"\x12SolicitudStreaming\x12 \n" +
	"\vrutaArchivo\x18\x01 \x01(\tR\vrutaArchivo\"&\n" +
	"\x0eFragmentoAudio\x12\x14\n" +
	"\x05datos\x18\x01 \x01(\fR\x05datos2b\n" +
	"\x11ServicioStreaming\x12M\n" +
	"\x0fReproducirAudio\x12\x1d.streaming.SolicitudStreaming\x1a\x19.streaming.FragmentoAudio0\x01B\x15Z\x13/serviciosStreamingb\x06proto3"

var (
	file_streaming_proto_rawDescOnce sync.Once
	file_streaming_proto_rawDescData []byte
)

func file_streaming_proto_rawDescGZIP() []byte {
	file_streaming_proto_rawDescOnce.Do(func() {
		file_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)))
	})
	return file_streaming_proto_rawDescData
}

var file_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streaming_proto_goTypes = []any{
	(*SolicitudStreaming)(nil), // 0: streaming.SolicitudStreaming
	(*FragmentoAudio)(nil),     // 1: streaming.FragmentoAudio
}
var file_streaming_proto_depIdxs = []int32{
	0, // 0: streaming.ServicioStreaming.ReproducirAudio:input_type -> streaming.SolicitudStreaming
	1, // 1: streaming.ServicioStreaming.ReproducirAudio:output_type -> streaming.FragmentoAudio
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streaming_proto_init() }
func file_streaming_proto_init() {
	if File_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_proto_goTypes,
		DependencyIndexes: file_streaming_proto_depIdxs,
		MessageInfos:      file_streaming_proto_msgTypes,
	}.Build()
	File_streaming_proto = out.File
	file_streaming_proto_goTypes = nil
	file_streaming_proto_depIdxs = nil
}
