// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: streaming.proto

package serviciosStreaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServicioStreaming_ReproducirAudio_FullMethodName = "/streaming.ServicioStreaming/ReproducirAudio"
)

// ServicioStreamingClient is the client API for ServicioStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio de streaming de audio en formato mp3
type ServicioStreamingClient interface {
	// Transmite un archivo de audio en fragmentos (chunks)
	ReproducirAudio(ctx context.Context, in *SolicitudStreaming, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FragmentoAudio], error)
}

type servicioStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewServicioStreamingClient(cc grpc.ClientConnInterface) ServicioStreamingClient {
	return &servicioStreamingClient{cc}
}

func (c *servicioStreamingClient) ReproducirAudio(ctx context.Context, in *SolicitudStreaming, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FragmentoAudio], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServicioStreaming_ServiceDesc.Streams[0], ServicioStreaming_ReproducirAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SolicitudStreaming, FragmentoAudio]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServicioStreaming_ReproducirAudioClient = grpc.ServerStreamingClient[FragmentoAudio]

// ServicioStreamingServer is the server API for ServicioStreaming service.
// All implementations must embed UnimplementedServicioStreamingServer
// for forward compatibility.
//
// Servicio de streaming de audio en formato mp3
type ServicioStreamingServer interface {
	// Transmite un archivo de audio en fragmentos (chunks)
	ReproducirAudio(*SolicitudStreaming, grpc.ServerStreamingServer[FragmentoAudio]) error
	mustEmbedUnimplementedServicioStreamingServer()
}

// UnimplementedServicioStreamingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicioStreamingServer struct{}

func (UnimplementedServicioStreamingServer) ReproducirAudio(*SolicitudStreaming, grpc.ServerStreamingServer[FragmentoAudio]) error {
	return status.Error(codes.Unimplemented, "method ReproducirAudio not implemented")
}
func (UnimplementedServicioStreamingServer) mustEmbedUnimplementedServicioStreamingServer() {}
func (UnimplementedServicioStreamingServer) testEmbeddedByValue()                           {}

// UnsafeServicioStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicioStreamingServer will
// result in compilation errors.
type UnsafeServicioStreamingServer interface {
	mustEmbedUnimplementedServicioStreamingServer()
}

func RegisterServicioStreamingServer(s grpc.ServiceRegistrar, srv ServicioStreamingServer) {
	// If the following call panics, it indicates UnimplementedServicioStreamingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicioStreaming_ServiceDesc, srv)
}

func _ServicioStreaming_ReproducirAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SolicitudStreaming)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServicioStreamingServer).ReproducirAudio(m, &grpc.GenericServerStream[SolicitudStreaming, FragmentoAudio]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServicioStreaming_ReproducirAudioServer = grpc.ServerStreamingServer[FragmentoAudio]

// ServicioStreaming_ServiceDesc is the grpc.ServiceDesc for ServicioStreaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicioStreaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.ServicioStreaming",
	HandlerType: (*ServicioStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReproducirAudio",
			Handler:       _ServicioStreaming_ReproducirAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streaming.proto",
}
