// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: protos/audio_metadata.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_GetAudioTypes_FullMethodName    = "/servicios.MetadataService/GetAudioTypes"
	MetadataService_GetAudiosByType_FullMethodName  = "/servicios.MetadataService/GetAudiosByType"
	MetadataService_GetAudioDetails_FullMethodName  = "/servicios.MetadataService/GetAudioDetails"
	MetadataService_GetAudioFilename_FullMethodName = "/servicios.MetadataService/GetAudioFilename"
	MetadataService_BuscarAudio_FullMethodName      = "/servicios.MetadataService/BuscarAudio"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataServiceClient interface {
	GetAudioTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AudioTypesResponse, error)
	GetAudiosByType(ctx context.Context, in *AudioTypeRequest, opts ...grpc.CallOption) (*AudiosListResponse, error)
	GetAudioDetails(ctx context.Context, in *AudioDetailsRequest, opts ...grpc.CallOption) (*AudioDetailsResponse, error)
	GetAudioFilename(ctx context.Context, in *AudioFilenameRequest, opts ...grpc.CallOption) (*AudioFilenameResponse, error)
	BuscarAudio(ctx context.Context, in *PeticionDTO, opts ...grpc.CallOption) (*RespuestaMetadataAudioDTO, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) GetAudioTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AudioTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioTypesResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetAudioTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetAudiosByType(ctx context.Context, in *AudioTypeRequest, opts ...grpc.CallOption) (*AudiosListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudiosListResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetAudiosByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetAudioDetails(ctx context.Context, in *AudioDetailsRequest, opts ...grpc.CallOption) (*AudioDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioDetailsResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetAudioDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetAudioFilename(ctx context.Context, in *AudioFilenameRequest, opts ...grpc.CallOption) (*AudioFilenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioFilenameResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetAudioFilename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) BuscarAudio(ctx context.Context, in *PeticionDTO, opts ...grpc.CallOption) (*RespuestaMetadataAudioDTO, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaMetadataAudioDTO)
	err := c.cc.Invoke(ctx, MetadataService_BuscarAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
type MetadataServiceServer interface {
	GetAudioTypes(context.Context, *Empty) (*AudioTypesResponse, error)
	GetAudiosByType(context.Context, *AudioTypeRequest) (*AudiosListResponse, error)
	GetAudioDetails(context.Context, *AudioDetailsRequest) (*AudioDetailsResponse, error)
	GetAudioFilename(context.Context, *AudioFilenameRequest) (*AudioFilenameResponse, error)
	BuscarAudio(context.Context, *PeticionDTO) (*RespuestaMetadataAudioDTO, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) GetAudioTypes(context.Context, *Empty) (*AudioTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAudioTypes not implemented")
}
func (UnimplementedMetadataServiceServer) GetAudiosByType(context.Context, *AudioTypeRequest) (*AudiosListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAudiosByType not implemented")
}
func (UnimplementedMetadataServiceServer) GetAudioDetails(context.Context, *AudioDetailsRequest) (*AudioDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAudioDetails not implemented")
}
func (UnimplementedMetadataServiceServer) GetAudioFilename(context.Context, *AudioFilenameRequest) (*AudioFilenameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAudioFilename not implemented")
}
func (UnimplementedMetadataServiceServer) BuscarAudio(context.Context, *PeticionDTO) (*RespuestaMetadataAudioDTO, error) {
	return nil, status.Error(codes.Unimplemented, "method BuscarAudio not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call panics, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_GetAudioTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetAudioTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetAudioTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetAudioTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetAudiosByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetAudiosByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetAudiosByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetAudiosByType(ctx, req.(*AudioTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetAudioDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetAudioDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetAudioDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetAudioDetails(ctx, req.(*AudioDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetAudioFilename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioFilenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetAudioFilename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetAudioFilename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetAudioFilename(ctx, req.(*AudioFilenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_BuscarAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeticionDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).BuscarAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_BuscarAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).BuscarAudio(ctx, req.(*PeticionDTO))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicios.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAudioTypes",
			Handler:    _MetadataService_GetAudioTypes_Handler,
		},
		{
			MethodName: "GetAudiosByType",
			Handler:    _MetadataService_GetAudiosByType_Handler,
		},
		{
			MethodName: "GetAudioDetails",
			Handler:    _MetadataService_GetAudioDetails_Handler,
		},
		{
			MethodName: "GetAudioFilename",
			Handler:    _MetadataService_GetAudioFilename_Handler,
		},
		{
			MethodName: "BuscarAudio",
			Handler:    _MetadataService_BuscarAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/audio_metadata.proto",
}
