// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/audio_streaming.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_protos_audio_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_protos_audio_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_protos_audio_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_protos_audio_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AudioFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFileRequest) Reset() {
	*x = AudioFileRequest{}
	mi := &file_protos_audio_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFileRequest) ProtoMessage() {}

func (x *AudioFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFileRequest.ProtoReflect.Descriptor instead.
func (*AudioFileRequest) Descriptor() ([]byte, []int) {
	return file_protos_audio_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *AudioFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AudioFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AudioFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AudioId       string                 `protobuf:"bytes,3,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFileResponse) Reset() {
	*x = AudioFileResponse{}
	mi := &file_protos_audio_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFileResponse) ProtoMessage() {}

func (x *AudioFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFileResponse.ProtoReflect.Descriptor instead.
func (*AudioFileResponse) Descriptor() ([]byte, []int) {
	return file_protos_audio_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *AudioFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AudioFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AudioFileResponse) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

type CallbackRegistroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallbackUrl   string                 `protobuf:"bytes,1,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRegistroRequest) Reset() {
	*x = CallbackRegistroRequest{}
	mi := &file_protos_audio_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRegistroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRegistroRequest) ProtoMessage() {}

func (x *CallbackRegistroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRegistroRequest.ProtoReflect.Descriptor instead.
func (*CallbackRegistroRequest) Descriptor() ([]byte, []int) {
	return file_protos_audio_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *CallbackRegistroRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type CallbackRegistroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRegistroResponse) Reset() {
	*x = CallbackRegistroResponse{}
	mi := &file_protos_audio_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRegistroResponse) ProtoMessage() {}

func (x *CallbackRegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRegistroResponse.ProtoReflect.Descriptor instead.
func (*CallbackRegistroResponse) Descriptor() ([]byte, []int) {
	return file_protos_audio_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *CallbackRegistroResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallbackRegistroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CallbackNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	FechaHora     string                 `protobuf:"bytes,3,opt,name=fecha_hora,json=fechaHora,proto3" json:"fecha_hora,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackNotification) Reset() {
	*x = CallbackNotification{}
	mi := &file_protos_audio_streaming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackNotification) ProtoMessage() {}

func (x *CallbackNotification) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_streaming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackNotification.ProtoReflect.Descriptor instead.
func (*CallbackNotification) Descriptor() ([]byte, []int) {
	return file_protos_audio_streaming_proto_rawDescGZIP(), []int{6}
}

func (x *CallbackNotification) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *CallbackNotification) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *CallbackNotification) GetFechaHora() string {
	if x != nil {
		return x.FechaHora
	}
	return ""
}

var File_protos_audio_streaming_proto protoreflect.FileDescriptor

const file_protos_audio_streaming_proto_rawDesc = "" +
	"\n" +
	"\x1cprotos/audio_streaming.proto\x12\tservicios\"*\n" +
	"\rStreamRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\" \n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"B\n" +
	"\x10AudioFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"b\n" +
	"\x11AudioFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\baudio_id\x18\x03 \x01(\tR\aaudioId\"<\n" +
	"\x17CallbackRegistroRequest\x12!\n" +
	"\fcallback_url\x18\x01 \x01(\tR\vcallbackUrl\"N\n" +
	"\x18CallbackRegistroResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\x14CallbackNotification\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x1d\n" +
	"\n" +
	"fecha_hora\x18\x03 \x01(\tR\tfechaHora2\xff\x01\n" +
	"\x10StreamingService\x12@\n" +
	"\vStreamAudio\x12\x18.servicios.StreamRequest\x1a\x15.servicios.AudioChunk0\x01\x12K\n" +
	"\x0eAlmacenarAudio\x12\x1b.servicios.AudioFileRequest\x1a\x1c.servicios.AudioFileResponse\x12\\\n" +
	"\x11RegistrarCallback\x12\".servicios.CallbackRegistroRequest\x1a#.servicios.CallbackRegistroResponseB\tZ\a/protosb\x06proto3"

var (
	file_protos_audio_streaming_proto_rawDescOnce sync.Once
	file_protos_audio_streaming_proto_rawDescData []byte
)

func file_protos_audio_streaming_proto_rawDescGZIP() []byte {
	file_protos_audio_streaming_proto_rawDescOnce.Do(func() {
		file_protos_audio_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_audio_streaming_proto_rawDesc), len(file_protos_audio_streaming_proto_rawDesc)))
	})
	return file_protos_audio_streaming_proto_rawDescData
}

var file_protos_audio_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_audio_streaming_proto_goTypes = []any{
	(*StreamRequest)(nil),            // 0: servicios.StreamRequest
	(*AudioChunk)(nil),               // 1: servicios.AudioChunk
	(*AudioFileRequest)(nil),         // 2: servicios.AudioFileRequest
	(*AudioFileResponse)(nil),        // 3: servicios.AudioFileResponse
	(*CallbackRegistroRequest)(nil),  // 4: servicios.CallbackRegistroRequest
	(*CallbackRegistroResponse)(nil), // 5: servicios.CallbackRegistroResponse
	(*CallbackNotification)(nil),     // 6: servicios.CallbackNotification
}
var file_protos_audio_streaming_proto_depIdxs = []int32{
	0, // 0: servicios.StreamingService.StreamAudio:input_type -> servicios.StreamRequest
	2, // 1: servicios.StreamingService.AlmacenarAudio:input_type -> servicios.AudioFileRequest
	4, // 2: servicios.StreamingService.RegistrarCallback:input_type -> servicios.CallbackRegistroRequest
	1, // 3: servicios.StreamingService.StreamAudio:output_type -> servicios.AudioChunk
	3, // 4: servicios.StreamingService.AlmacenarAudio:output_type -> servicios.AudioFileResponse
	5, // 5: servicios.StreamingService.RegistrarCallback:output_type -> servicios.CallbackRegistroResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_audio_streaming_proto_init() }
func file_protos_audio_streaming_proto_init() {
	if File_protos_audio_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_audio_streaming_proto_rawDesc), len(file_protos_audio_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_audio_streaming_proto_goTypes,
		DependencyIndexes: file_protos_audio_streaming_proto_depIdxs,
		MessageInfos:      file_protos_audio_streaming_proto_msgTypes,
	}.Build()
	File_protos_audio_streaming_proto = out.File
	file_protos_audio_streaming_proto_goTypes = nil
	file_protos_audio_streaming_proto_depIdxs = nil
}
