spring.application.name=administrador
server.port=8080

# Servidor de Metadatos (Go - REST)
servidor.metadatos.host=localhost
servidor.metadatos.puerto=8090

# Servidor de Streaming (Go - gRPC)
servidor.streaming.host=localhost
servidor.streaming.puerto=50052

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB