/**
 * @fileoverview gRPC-Web generated client stub for servicios
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v4.25.2
// source: servicios.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.servicios = require('./servicios_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.servicios.AudioServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.servicios.AudioServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.servicios.peticionDTO,
 *   !proto.servicios.fragmentoCancion>}
 */
const methodDescriptor_AudioService_enviarCancionMedianteStream = new grpc.web.MethodDescriptor(
  '/servicios.AudioService/enviarCancionMedianteStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.servicios.peticionDTO,
  proto.servicios.fragmentoCancion,
  /**
   * @param {!proto.servicios.peticionDTO} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.servicios.fragmentoCancion.deserializeBinary
);


/**
 * @param {!proto.servicios.peticionDTO} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.servicios.fragmentoCancion>}
 *     The XHR Node Readable Stream
 */
proto.servicios.AudioServiceClient.prototype.enviarCancionMedianteStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/servicios.AudioService/enviarCancionMedianteStream',
      request,
      metadata || {},
      methodDescriptor_AudioService_enviarCancionMedianteStream);
};


/**
 * @param {!proto.servicios.peticionDTO} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.servicios.fragmentoCancion>}
 *     The XHR Node Readable Stream
 */
proto.servicios.AudioServicePromiseClient.prototype.enviarCancionMedianteStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/servicios.AudioService/enviarCancionMedianteStream',
      request,
      metadata || {},
      methodDescriptor_AudioService_enviarCancionMedianteStream);
};


module.exports = proto.servicios;

