// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: metadatos.proto

package serviciosMetadatos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServicioMetadatos_ObtenerTiposDeAudio_FullMethodName  = "/metadatos.ServicioMetadatos/ObtenerTiposDeAudio"
	ServicioMetadatos_ObtenerAudiosPorTipo_FullMethodName = "/metadatos.ServicioMetadatos/ObtenerAudiosPorTipo"
	ServicioMetadatos_ObtenerDetallesAudio_FullMethodName = "/metadatos.ServicioMetadatos/ObtenerDetallesAudio"
)

// ServicioMetadatosClient is the client API for ServicioMetadatos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────
// Servicio de metadatos de audios
// ─────────────────────────────────────────────
type ServicioMetadatosClient interface {
	// Obtiene todos los tipos de audio registrados
	ObtenerTiposDeAudio(ctx context.Context, in *SolicitudVacia, opts ...grpc.CallOption) (*RespuestaTiposAudio, error)
	// Obtiene la lista de audios de un tipo dado su id
	ObtenerAudiosPorTipo(ctx context.Context, in *SolicitudTipo, opts ...grpc.CallOption) (*RespuestaListaAudios, error)
	// Obtiene los detalles (metadatos) de un audio dado su id
	ObtenerDetallesAudio(ctx context.Context, in *SolicitudAudio, opts ...grpc.CallOption) (*RespuestaDetallesAudio, error)
}

type servicioMetadatosClient struct {
	cc grpc.ClientConnInterface
}

func NewServicioMetadatosClient(cc grpc.ClientConnInterface) ServicioMetadatosClient {
	return &servicioMetadatosClient{cc}
}

func (c *servicioMetadatosClient) ObtenerTiposDeAudio(ctx context.Context, in *SolicitudVacia, opts ...grpc.CallOption) (*RespuestaTiposAudio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaTiposAudio)
	err := c.cc.Invoke(ctx, ServicioMetadatos_ObtenerTiposDeAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioMetadatosClient) ObtenerAudiosPorTipo(ctx context.Context, in *SolicitudTipo, opts ...grpc.CallOption) (*RespuestaListaAudios, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaListaAudios)
	err := c.cc.Invoke(ctx, ServicioMetadatos_ObtenerAudiosPorTipo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioMetadatosClient) ObtenerDetallesAudio(ctx context.Context, in *SolicitudAudio, opts ...grpc.CallOption) (*RespuestaDetallesAudio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaDetallesAudio)
	err := c.cc.Invoke(ctx, ServicioMetadatos_ObtenerDetallesAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicioMetadatosServer is the server API for ServicioMetadatos service.
// All implementations must embed UnimplementedServicioMetadatosServer
// for forward compatibility.
//
// ─────────────────────────────────────────────
// Servicio de metadatos de audios
// ─────────────────────────────────────────────
type ServicioMetadatosServer interface {
	// Obtiene todos los tipos de audio registrados
	ObtenerTiposDeAudio(context.Context, *SolicitudVacia) (*RespuestaTiposAudio, error)
	// Obtiene la lista de audios de un tipo dado su id
	ObtenerAudiosPorTipo(context.Context, *SolicitudTipo) (*RespuestaListaAudios, error)
	// Obtiene los detalles (metadatos) de un audio dado su id
	ObtenerDetallesAudio(context.Context, *SolicitudAudio) (*RespuestaDetallesAudio, error)
	mustEmbedUnimplementedServicioMetadatosServer()
}

// UnimplementedServicioMetadatosServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicioMetadatosServer struct{}

func (UnimplementedServicioMetadatosServer) ObtenerTiposDeAudio(context.Context, *SolicitudVacia) (*RespuestaTiposAudio, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerTiposDeAudio not implemented")
}
func (UnimplementedServicioMetadatosServer) ObtenerAudiosPorTipo(context.Context, *SolicitudTipo) (*RespuestaListaAudios, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerAudiosPorTipo not implemented")
}
func (UnimplementedServicioMetadatosServer) ObtenerDetallesAudio(context.Context, *SolicitudAudio) (*RespuestaDetallesAudio, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerDetallesAudio not implemented")
}
func (UnimplementedServicioMetadatosServer) mustEmbedUnimplementedServicioMetadatosServer() {}
func (UnimplementedServicioMetadatosServer) testEmbeddedByValue()                           {}

// UnsafeServicioMetadatosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicioMetadatosServer will
// result in compilation errors.
type UnsafeServicioMetadatosServer interface {
	mustEmbedUnimplementedServicioMetadatosServer()
}

func RegisterServicioMetadatosServer(s grpc.ServiceRegistrar, srv ServicioMetadatosServer) {
	// If the following call panics, it indicates UnimplementedServicioMetadatosServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicioMetadatos_ServiceDesc, srv)
}

func _ServicioMetadatos_ObtenerTiposDeAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudVacia)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioMetadatosServer).ObtenerTiposDeAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioMetadatos_ObtenerTiposDeAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioMetadatosServer).ObtenerTiposDeAudio(ctx, req.(*SolicitudVacia))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicioMetadatos_ObtenerAudiosPorTipo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudTipo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioMetadatosServer).ObtenerAudiosPorTipo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioMetadatos_ObtenerAudiosPorTipo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioMetadatosServer).ObtenerAudiosPorTipo(ctx, req.(*SolicitudTipo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicioMetadatos_ObtenerDetallesAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudAudio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioMetadatosServer).ObtenerDetallesAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioMetadatos_ObtenerDetallesAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioMetadatosServer).ObtenerDetallesAudio(ctx, req.(*SolicitudAudio))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicioMetadatos_ServiceDesc is the grpc.ServiceDesc for ServicioMetadatos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicioMetadatos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metadatos.ServicioMetadatos",
	HandlerType: (*ServicioMetadatosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerTiposDeAudio",
			Handler:    _ServicioMetadatos_ObtenerTiposDeAudio_Handler,
		},
		{
			MethodName: "ObtenerAudiosPorTipo",
			Handler:    _ServicioMetadatos_ObtenerAudiosPorTipo_Handler,
		},
		{
			MethodName: "ObtenerDetallesAudio",
			Handler:    _ServicioMetadatos_ObtenerDetallesAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadatos.proto",
}
