// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: metadatos.proto

package serviciosMetadatos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── Mensajes generales ───────────────────────
type SolicitudVacia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudVacia) Reset() {
	*x = SolicitudVacia{}
	mi := &file_metadatos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudVacia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudVacia) ProtoMessage() {}

func (x *SolicitudVacia) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudVacia.ProtoReflect.Descriptor instead.
func (*SolicitudVacia) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{0}
}

type SolicitudTipo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTipo        int32                  `protobuf:"varint,1,opt,name=idTipo,proto3" json:"idTipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudTipo) Reset() {
	*x = SolicitudTipo{}
	mi := &file_metadatos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudTipo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudTipo) ProtoMessage() {}

func (x *SolicitudTipo) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudTipo.ProtoReflect.Descriptor instead.
func (*SolicitudTipo) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{1}
}

func (x *SolicitudTipo) GetIdTipo() int32 {
	if x != nil {
		return x.IdTipo
	}
	return 0
}

type SolicitudAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdAudio       int32                  `protobuf:"varint,1,opt,name=idAudio,proto3" json:"idAudio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudAudio) Reset() {
	*x = SolicitudAudio{}
	mi := &file_metadatos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudAudio) ProtoMessage() {}

func (x *SolicitudAudio) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudAudio.ProtoReflect.Descriptor instead.
func (*SolicitudAudio) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{2}
}

func (x *SolicitudAudio) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

// ─── Tipos de audio ───────────────────────────
type TipoAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TipoAudio) Reset() {
	*x = TipoAudio{}
	mi := &file_metadatos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TipoAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipoAudio) ProtoMessage() {}

func (x *TipoAudio) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipoAudio.ProtoReflect.Descriptor instead.
func (*TipoAudio) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{3}
}

func (x *TipoAudio) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TipoAudio) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type RespuestaTiposAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tipos         []*TipoAudio           `protobuf:"bytes,1,rep,name=tipos,proto3" json:"tipos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaTiposAudio) Reset() {
	*x = RespuestaTiposAudio{}
	mi := &file_metadatos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaTiposAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaTiposAudio) ProtoMessage() {}

func (x *RespuestaTiposAudio) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaTiposAudio.ProtoReflect.Descriptor instead.
func (*RespuestaTiposAudio) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{4}
}

func (x *RespuestaTiposAudio) GetTipos() []*TipoAudio {
	if x != nil {
		return x.Tipos
	}
	return nil
}

// ─── Lista de audios ──────────────────────────
type AudioResumen struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo         string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	RutaArchivoMp3 string                 `protobuf:"bytes,3,opt,name=rutaArchivoMp3,proto3" json:"rutaArchivoMp3,omitempty"` // ruta usada por el servidor de streaming
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AudioResumen) Reset() {
	*x = AudioResumen{}
	mi := &file_metadatos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioResumen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioResumen) ProtoMessage() {}

func (x *AudioResumen) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioResumen.ProtoReflect.Descriptor instead.
func (*AudioResumen) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{5}
}

func (x *AudioResumen) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioResumen) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *AudioResumen) GetRutaArchivoMp3() string {
	if x != nil {
		return x.RutaArchivoMp3
	}
	return ""
}

type RespuestaListaAudios struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audios        []*AudioResumen        `protobuf:"bytes,1,rep,name=audios,proto3" json:"audios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaListaAudios) Reset() {
	*x = RespuestaListaAudios{}
	mi := &file_metadatos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaListaAudios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaListaAudios) ProtoMessage() {}

func (x *RespuestaListaAudios) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaListaAudios.ProtoReflect.Descriptor instead.
func (*RespuestaListaAudios) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{6}
}

func (x *RespuestaListaAudios) GetAudios() []*AudioResumen {
	if x != nil {
		return x.Audios
	}
	return nil
}

// Música
type MetadataMusica struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ArtistaPrincipal  string                 `protobuf:"bytes,1,opt,name=artistaPrincipal,proto3" json:"artistaPrincipal,omitempty"`
	Album             string                 `protobuf:"bytes,2,opt,name=album,proto3" json:"album,omitempty"`
	GeneroMusical     string                 `protobuf:"bytes,3,opt,name=generoMusical,proto3" json:"generoMusical,omitempty"`
	TituloCancion     string                 `protobuf:"bytes,4,opt,name=tituloCancion,proto3" json:"tituloCancion,omitempty"`
	SelloDiscografico string                 `protobuf:"bytes,5,opt,name=selloDiscografico,proto3" json:"selloDiscografico,omitempty"`
	AnioLanzamiento   int32                  `protobuf:"varint,6,opt,name=anioLanzamiento,proto3" json:"anioLanzamiento,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetadataMusica) Reset() {
	*x = MetadataMusica{}
	mi := &file_metadatos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataMusica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataMusica) ProtoMessage() {}

func (x *MetadataMusica) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataMusica.ProtoReflect.Descriptor instead.
func (*MetadataMusica) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{7}
}

func (x *MetadataMusica) GetArtistaPrincipal() string {
	if x != nil {
		return x.ArtistaPrincipal
	}
	return ""
}

func (x *MetadataMusica) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *MetadataMusica) GetGeneroMusical() string {
	if x != nil {
		return x.GeneroMusical
	}
	return ""
}

func (x *MetadataMusica) GetTituloCancion() string {
	if x != nil {
		return x.TituloCancion
	}
	return ""
}

func (x *MetadataMusica) GetSelloDiscografico() string {
	if x != nil {
		return x.SelloDiscografico
	}
	return ""
}

func (x *MetadataMusica) GetAnioLanzamiento() int32 {
	if x != nil {
		return x.AnioLanzamiento
	}
	return 0
}

// Podcast
type MetadataPodcast struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NombrePodcast          string                 `protobuf:"bytes,1,opt,name=nombrePodcast,proto3" json:"nombrePodcast,omitempty"`
	TituloEpisodio         string                 `protobuf:"bytes,2,opt,name=tituloEpisodio,proto3" json:"tituloEpisodio,omitempty"`
	Host                   string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	TemporadaEpisodio      string                 `protobuf:"bytes,4,opt,name=temporadaEpisodio,proto3" json:"temporadaEpisodio,omitempty"`
	NotasShow              string                 `protobuf:"bytes,5,opt,name=notasShow,proto3" json:"notasShow,omitempty"`
	ClasificacionContenido string                 `protobuf:"bytes,6,opt,name=clasificacionContenido,proto3" json:"clasificacionContenido,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MetadataPodcast) Reset() {
	*x = MetadataPodcast{}
	mi := &file_metadatos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataPodcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataPodcast) ProtoMessage() {}

func (x *MetadataPodcast) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataPodcast.ProtoReflect.Descriptor instead.
func (*MetadataPodcast) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{8}
}

func (x *MetadataPodcast) GetNombrePodcast() string {
	if x != nil {
		return x.NombrePodcast
	}
	return ""
}

func (x *MetadataPodcast) GetTituloEpisodio() string {
	if x != nil {
		return x.TituloEpisodio
	}
	return ""
}

func (x *MetadataPodcast) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MetadataPodcast) GetTemporadaEpisodio() string {
	if x != nil {
		return x.TemporadaEpisodio
	}
	return ""
}

func (x *MetadataPodcast) GetNotasShow() string {
	if x != nil {
		return x.NotasShow
	}
	return ""
}

func (x *MetadataPodcast) GetClasificacionContenido() string {
	if x != nil {
		return x.ClasificacionContenido
	}
	return ""
}

// Audiolibro
type MetadataAudiolibro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TituloLibro   string                 `protobuf:"bytes,1,opt,name=tituloLibro,proto3" json:"tituloLibro,omitempty"`
	Autor         string                 `protobuf:"bytes,2,opt,name=autor,proto3" json:"autor,omitempty"`
	Narrador      string                 `protobuf:"bytes,3,opt,name=narrador,proto3" json:"narrador,omitempty"`
	Editorial     string                 `protobuf:"bytes,4,opt,name=editorial,proto3" json:"editorial,omitempty"`
	Isbn          string                 `protobuf:"bytes,5,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Capitulo      int32                  `protobuf:"varint,6,opt,name=capitulo,proto3" json:"capitulo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataAudiolibro) Reset() {
	*x = MetadataAudiolibro{}
	mi := &file_metadatos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataAudiolibro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataAudiolibro) ProtoMessage() {}

func (x *MetadataAudiolibro) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataAudiolibro.ProtoReflect.Descriptor instead.
func (*MetadataAudiolibro) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{9}
}

func (x *MetadataAudiolibro) GetTituloLibro() string {
	if x != nil {
		return x.TituloLibro
	}
	return ""
}

func (x *MetadataAudiolibro) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *MetadataAudiolibro) GetNarrador() string {
	if x != nil {
		return x.Narrador
	}
	return ""
}

func (x *MetadataAudiolibro) GetEditorial() string {
	if x != nil {
		return x.Editorial
	}
	return ""
}

func (x *MetadataAudiolibro) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *MetadataAudiolibro) GetCapitulo() int32 {
	if x != nil {
		return x.Capitulo
	}
	return 0
}

// Ruido Blanco
type MetadataRuidoBlanco struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TipoSonido          string                 `protobuf:"bytes,1,opt,name=tipoSonido,proto3" json:"tipoSonido,omitempty"`
	FuenteAudio         string                 `protobuf:"bytes,2,opt,name=fuenteAudio,proto3" json:"fuenteAudio,omitempty"`
	UsoSugerido         string                 `protobuf:"bytes,3,opt,name=usoSugerido,proto3" json:"usoSugerido,omitempty"`
	ProveedorContenido  string                 `protobuf:"bytes,4,opt,name=proveedorContenido,proto3" json:"proveedorContenido,omitempty"`
	DuracionBucle       string                 `protobuf:"bytes,5,opt,name=duracionBucle,proto3" json:"duracionBucle,omitempty"`
	FrecuenciaDominante string                 `protobuf:"bytes,6,opt,name=frecuenciaDominante,proto3" json:"frecuenciaDominante,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MetadataRuidoBlanco) Reset() {
	*x = MetadataRuidoBlanco{}
	mi := &file_metadatos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRuidoBlanco) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRuidoBlanco) ProtoMessage() {}

func (x *MetadataRuidoBlanco) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRuidoBlanco.ProtoReflect.Descriptor instead.
func (*MetadataRuidoBlanco) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{10}
}

func (x *MetadataRuidoBlanco) GetTipoSonido() string {
	if x != nil {
		return x.TipoSonido
	}
	return ""
}

func (x *MetadataRuidoBlanco) GetFuenteAudio() string {
	if x != nil {
		return x.FuenteAudio
	}
	return ""
}

func (x *MetadataRuidoBlanco) GetUsoSugerido() string {
	if x != nil {
		return x.UsoSugerido
	}
	return ""
}

func (x *MetadataRuidoBlanco) GetProveedorContenido() string {
	if x != nil {
		return x.ProveedorContenido
	}
	return ""
}

func (x *MetadataRuidoBlanco) GetDuracionBucle() string {
	if x != nil {
		return x.DuracionBucle
	}
	return ""
}

func (x *MetadataRuidoBlanco) GetFrecuenciaDominante() string {
	if x != nil {
		return x.FrecuenciaDominante
	}
	return ""
}

// Respuesta de detalles: sólo uno de los campos estará lleno
type RespuestaDetallesAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resumen       *AudioResumen          `protobuf:"bytes,1,opt,name=resumen,proto3" json:"resumen,omitempty"`
	Musica        *MetadataMusica        `protobuf:"bytes,2,opt,name=musica,proto3" json:"musica,omitempty"`
	Podcast       *MetadataPodcast       `protobuf:"bytes,3,opt,name=podcast,proto3" json:"podcast,omitempty"`
	Audiolibro    *MetadataAudiolibro    `protobuf:"bytes,4,opt,name=audiolibro,proto3" json:"audiolibro,omitempty"`
	RuidoBlanco   *MetadataRuidoBlanco   `protobuf:"bytes,5,opt,name=ruidoBlanco,proto3" json:"ruidoBlanco,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaDetallesAudio) Reset() {
	*x = RespuestaDetallesAudio{}
	mi := &file_metadatos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaDetallesAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaDetallesAudio) ProtoMessage() {}

func (x *RespuestaDetallesAudio) ProtoReflect() protoreflect.Message {
	mi := &file_metadatos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaDetallesAudio.ProtoReflect.Descriptor instead.
func (*RespuestaDetallesAudio) Descriptor() ([]byte, []int) {
	return file_metadatos_proto_rawDescGZIP(), []int{11}
}

func (x *RespuestaDetallesAudio) GetResumen() *AudioResumen {
	if x != nil {
		return x.Resumen
	}
	return nil
}

func (x *RespuestaDetallesAudio) GetMusica() *MetadataMusica {
	if x != nil {
		return x.Musica
	}
	return nil
}

func (x *RespuestaDetallesAudio) GetPodcast() *MetadataPodcast {
	if x != nil {
		return x.Podcast
	}
	return nil
}

func (x *RespuestaDetallesAudio) GetAudiolibro() *MetadataAudiolibro {
	if x != nil {
		return x.Audiolibro
	}
	return nil
}

func (x *RespuestaDetallesAudio) GetRuidoBlanco() *MetadataRuidoBlanco {
	if x != nil {
		return x.RuidoBlanco
	}
	return nil
}

var File_metadatos_proto protoreflect.FileDescriptor

const file_metadatos_proto_rawDesc = "" +
	"\n" +
	"\x0fmetadatos.proto\x12\tmetadatos\"\x10\n" +
	"\x0eSolicitudVacia\"'\n" +
	"\rSolicitudTipo\x12\x16\n" +
	"\x06idTipo\x18\x01 \x01(\x05R\x06idTipo\"*\n" +
	"\x0eSolicitudAudio\x12\x18\n" +
	"\aidAudio\x18\x01 \x01(\x05R\aidAudio\"3\n" +
	"\tTipoAudio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\"A\n" +
	"\x13RespuestaTiposAudio\x12*\n" +
	"\x05tipos\x18\x01 \x03(\v2\x14.metadatos.TipoAudioR\x05tipos\"^\n" +
	"\fAudioResumen\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12&\n" +
	"\x0erutaArchivoMp3\x18\x03 \x01(\tR\x0erutaArchivoMp3\"G\n" +
	"\x14RespuestaListaAudios\x12/\n" +
	"\x06audios\x18\x01 \x03(\v2\x17.metadatos.AudioResumenR\x06audios\"\xf6\x01\n" +
	"\x0eMetadataMusica\x12*\n" +
	"\x10artistaPrincipal\x18\x01 \x01(\tR\x10artistaPrincipal\x12\x14\n" +
	"\x05album\x18\x02 \x01(\tR\x05album\x12$\n" +
	"\rgeneroMusical\x18\x03 \x01(\tR\rgeneroMusical\x12$\n" +
	"\rtituloCancion\x18\x04 \x01(\tR\rtituloCancion\x12,\n" +
	"\x11selloDiscografico\x18\x05 \x01(\tR\x11selloDiscografico\x12(\n" +
	"\x0fanioLanzamiento\x18\x06 \x01(\x05R\x0fanioLanzamiento\"\xf7\x01\n" +
	"\x0fMetadataPodcast\x12$\n" +
	"\rnombrePodcast\x18\x01 \x01(\tR\rnombrePodcast\x12&\n" +
	"\x0etituloEpisodio\x18\x02 \x01(\tR\x0etituloEpisodio\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12,\n" +
	"\x11temporadaEpisodio\x18\x04 \x01(\tR\x11temporadaEpisodio\x12\x1c\n" +
	"\tnotasShow\x18\x05 \x01(\tR\tnotasShow\x126\n" +
	"\x16clasificacionContenido\x18\x06 \x01(\tR\x16clasificacionContenido\"\xb6\x01\n" +
	"\x12MetadataAudiolibro\x12 \n" +
	"\vtituloLibro\x18\x01 \x01(\tR\vtituloLibro\x12\x14\n" +
	"\x05autor\x18\x02 \x01(\tR\x05autor\x12\x1a\n" +
	"\bnarrador\x18\x03 \x01(\tR\bnarrador\x12\x1c\n" +
	"\teditorial\x18\x04 \x01(\tR\teditorial\x12\x12\n" +
	"\x04isbn\x18\x05 \x01(\tR\x04isbn\x12\x1a\n" +
	"\bcapitulo\x18\x06 \x01(\x05R\bcapitulo\"\x81\x02\n" +
	"\x13MetadataRuidoBlanco\x12\x1e\n" +
	"\n" +
	"tipoSonido\x18\x01 \x01(\tR\n" +
	"tipoSonido\x12 \n" +
	"\vfuenteAudio\x18\x02 \x01(\tR\vfuenteAudio\x12 \n" +
	"\vusoSugerido\x18\x03 \x01(\tR\vusoSugerido\x12.\n" +
	"\x12proveedorContenido\x18\x04 \x01(\tR\x12proveedorContenido\x12$\n" +
	"\rduracionBucle\x18\x05 \x01(\tR\rduracionBucle\x120\n" +
	"\x13frecuenciaDominante\x18\x06 \x01(\tR\x13frecuenciaDominante\"\xb5\x02\n" +
	"\x16RespuestaDetallesAudio\x121\n" +
	"\aresumen\x18\x01 \x01(\v2\x17.metadatos.AudioResumenR\aresumen\x121\n" +
	"\x06musica\x18\x02 \x01(\v2\x19.metadatos.MetadataMusicaR\x06musica\x124\n" +
	"\apodcast\x18\x03 \x01(\v2\x1a.metadatos.MetadataPodcastR\apodcast\x12=\n" +
	"\n" +
	"audiolibro\x18\x04 \x01(\v2\x1d.metadatos.MetadataAudiolibroR\n" +
	"audiolibro\x12@\n" +
	"\vruidoBlanco\x18\x05 \x01(\v2\x1e.metadatos.MetadataRuidoBlancoR\vruidoBlanco2\x8e\x02\n" +
	"\x11ServicioMetadatos\x12P\n" +
	"\x13ObtenerTiposDeAudio\x12\x19.metadatos.SolicitudVacia\x1a\x1e.metadatos.RespuestaTiposAudio\x12Q\n" +
	"\x14ObtenerAudiosPorTipo\x12\x18.metadatos.SolicitudTipo\x1a\x1f.metadatos.RespuestaListaAudios\x12T\n" +
	"\x14ObtenerDetallesAudio\x12\x19.metadatos.SolicitudAudio\x1a!.metadatos.RespuestaDetallesAudioB\x15Z\x13/serviciosMetadatosb\x06proto3"

var (
	file_metadatos_proto_rawDescOnce sync.Once
	file_metadatos_proto_rawDescData []byte
)

func file_metadatos_proto_rawDescGZIP() []byte {
	file_metadatos_proto_rawDescOnce.Do(func() {
		file_metadatos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadatos_proto_rawDesc), len(file_metadatos_proto_rawDesc)))
	})
	return file_metadatos_proto_rawDescData
}

var file_metadatos_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_metadatos_proto_goTypes = []any{
	(*SolicitudVacia)(nil),         // 0: metadatos.SolicitudVacia
	(*SolicitudTipo)(nil),          // 1: metadatos.SolicitudTipo
	(*SolicitudAudio)(nil),         // 2: metadatos.SolicitudAudio
	(*TipoAudio)(nil),              // 3: metadatos.TipoAudio
	(*RespuestaTiposAudio)(nil),    // 4: metadatos.RespuestaTiposAudio
	(*AudioResumen)(nil),           // 5: metadatos.AudioResumen
	(*RespuestaListaAudios)(nil),   // 6: metadatos.RespuestaListaAudios
	(*MetadataMusica)(nil),         // 7: metadatos.MetadataMusica
	(*MetadataPodcast)(nil),        // 8: metadatos.MetadataPodcast
	(*MetadataAudiolibro)(nil),     // 9: metadatos.MetadataAudiolibro
	(*MetadataRuidoBlanco)(nil),    // 10: metadatos.MetadataRuidoBlanco
	(*RespuestaDetallesAudio)(nil), // 11: metadatos.RespuestaDetallesAudio
}
var file_metadatos_proto_depIdxs = []int32{
	3,  // 0: metadatos.RespuestaTiposAudio.tipos:type_name -> metadatos.TipoAudio
	5,  // 1: metadatos.RespuestaListaAudios.audios:type_name -> metadatos.AudioResumen
	5,  // 2: metadatos.RespuestaDetallesAudio.resumen:type_name -> metadatos.AudioResumen
	7,  // 3: metadatos.RespuestaDetallesAudio.musica:type_name -> metadatos.MetadataMusica
	8,  // 4: metadatos.RespuestaDetallesAudio.podcast:type_name -> metadatos.MetadataPodcast
	9,  // 5: metadatos.RespuestaDetallesAudio.audiolibro:type_name -> metadatos.MetadataAudiolibro
	10, // 6: metadatos.RespuestaDetallesAudio.ruidoBlanco:type_name -> metadatos.MetadataRuidoBlanco
	0,  // 7: metadatos.ServicioMetadatos.ObtenerTiposDeAudio:input_type -> metadatos.SolicitudVacia
	1,  // 8: metadatos.ServicioMetadatos.ObtenerAudiosPorTipo:input_type -> metadatos.SolicitudTipo
	2,  // 9: metadatos.ServicioMetadatos.ObtenerDetallesAudio:input_type -> metadatos.SolicitudAudio
	4,  // 10: metadatos.ServicioMetadatos.ObtenerTiposDeAudio:output_type -> metadatos.RespuestaTiposAudio
	6,  // 11: metadatos.ServicioMetadatos.ObtenerAudiosPorTipo:output_type -> metadatos.RespuestaListaAudios
	11, // 12: metadatos.ServicioMetadatos.ObtenerDetallesAudio:output_type -> metadatos.RespuestaDetallesAudio
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_metadatos_proto_init() }
func file_metadatos_proto_init() {
	if File_metadatos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadatos_proto_rawDesc), len(file_metadatos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metadatos_proto_goTypes,
		DependencyIndexes: file_metadatos_proto_depIdxs,
		MessageInfos:      file_metadatos_proto_msgTypes,
	}.Build()
	File_metadatos_proto = out.File
	file_metadatos_proto_goTypes = nil
	file_metadatos_proto_depIdxs = nil
}
