// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: servicios.proto

package serviciosCancion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeticionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Formato       string                 `protobuf:"bytes,2,opt,name=formato,proto3" json:"formato,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionDTO) Reset() {
	*x = PeticionDTO{}
	mi := &file_servicios_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionDTO) ProtoMessage() {}

func (x *PeticionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionDTO.ProtoReflect.Descriptor instead.
func (*PeticionDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{0}
}

func (x *PeticionDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *PeticionDTO) GetFormato() string {
	if x != nil {
		return x.Formato
	}
	return ""
}

type FragmentoCancion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FragmentoCancion) Reset() {
	*x = FragmentoCancion{}
	mi := &file_servicios_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentoCancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentoCancion) ProtoMessage() {}

func (x *FragmentoCancion) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentoCancion.ProtoReflect.Descriptor instead.
func (*FragmentoCancion) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{1}
}

func (x *FragmentoCancion) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_servicios_proto protoreflect.FileDescriptor

const file_servicios_proto_rawDesc = "" +
	"\n" +
	"\x0fservicios.proto\x12\tservicios\"?\n" +
	"\vpeticionDTO\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\x12\x18\n" +
	"\aformato\x18\x02 \x01(\tR\aformato\"&\n" +
	"\x10fragmentoCancion\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2d\n" +
	"\fAudioService\x12T\n" +
	"\x1benviarCancionMedianteStream\x12\x16.servicios.peticionDTO\x1a\x1b.servicios.fragmentoCancion0\x01B\x13Z\x11/serviciosCancionb\x06proto3"

var (
	file_servicios_proto_rawDescOnce sync.Once
	file_servicios_proto_rawDescData []byte
)

func file_servicios_proto_rawDescGZIP() []byte {
	file_servicios_proto_rawDescOnce.Do(func() {
		file_servicios_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicios_proto_rawDesc), len(file_servicios_proto_rawDesc)))
	})
	return file_servicios_proto_rawDescData
}

var file_servicios_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_servicios_proto_goTypes = []any{
	(*PeticionDTO)(nil),      // 0: servicios.peticionDTO
	(*FragmentoCancion)(nil), // 1: servicios.fragmentoCancion
}
var file_servicios_proto_depIdxs = []int32{
	0, // 0: servicios.AudioService.enviarCancionMedianteStream:input_type -> servicios.peticionDTO
	1, // 1: servicios.AudioService.enviarCancionMedianteStream:output_type -> servicios.fragmentoCancion
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_servicios_proto_init() }
func file_servicios_proto_init() {
	if File_servicios_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicios_proto_rawDesc), len(file_servicios_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicios_proto_goTypes,
		DependencyIndexes: file_servicios_proto_depIdxs,
		MessageInfos:      file_servicios_proto_msgTypes,
	}.Build()
	File_servicios_proto = out.File
	file_servicios_proto_goTypes = nil
	file_servicios_proto_depIdxs = nil
}
