// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: servicios.proto

package serviciosCancion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeticionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionDTO) Reset() {
	*x = PeticionDTO{}
	mi := &file_servicios_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionDTO) ProtoMessage() {}

func (x *PeticionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionDTO.ProtoReflect.Descriptor instead.
func (*PeticionDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{0}
}

func (x *PeticionDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

type MetadataAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,3,opt,name=Titulo,proto3" json:"Titulo,omitempty"`
	Duracion      int32                  `protobuf:"varint,4,opt,name=Duracion,proto3" json:"Duracion,omitempty"`
	Tipo          string                 `protobuf:"bytes,5,opt,name=Tipo,proto3" json:"Tipo,omitempty"`
	Disponible    bool                   `protobuf:"varint,6,opt,name=Disponible,proto3" json:"Disponible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataAudio) Reset() {
	*x = MetadataAudio{}
	mi := &file_servicios_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataAudio) ProtoMessage() {}

func (x *MetadataAudio) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataAudio.ProtoReflect.Descriptor instead.
func (*MetadataAudio) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataAudio) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *MetadataAudio) GetDuracion() int32 {
	if x != nil {
		return x.Duracion
	}
	return 0
}

func (x *MetadataAudio) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *MetadataAudio) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

type RespuestaMetadataAudioDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Codigo        int32                  `protobuf:"varint,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	ObjAudio      *MetadataAudio         `protobuf:"bytes,3,opt,name=ObjAudio,proto3" json:"ObjAudio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaMetadataAudioDTO) Reset() {
	*x = RespuestaMetadataAudioDTO{}
	mi := &file_servicios_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaMetadataAudioDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaMetadataAudioDTO) ProtoMessage() {}

func (x *RespuestaMetadataAudioDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaMetadataAudioDTO.ProtoReflect.Descriptor instead.
func (*RespuestaMetadataAudioDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{2}
}

func (x *RespuestaMetadataAudioDTO) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaMetadataAudioDTO) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *RespuestaMetadataAudioDTO) GetObjAudio() *MetadataAudio {
	if x != nil {
		return x.ObjAudio
	}
	return nil
}

var File_servicios_proto protoreflect.FileDescriptor

const file_servicios_proto_rawDesc = "" +
	"\n" +
	"\x0fservicios.proto\x12\tservicios\"%\n" +
	"\vPeticionDTO\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\"w\n" +
	"\rMetadataAudio\x12\x16\n" +
	"\x06Titulo\x18\x03 \x01(\tR\x06Titulo\x12\x1a\n" +
	"\bDuracion\x18\x04 \x01(\x05R\bDuracion\x12\x12\n" +
	"\x04Tipo\x18\x05 \x01(\tR\x04Tipo\x12\x1e\n" +
	"\n" +
	"Disponible\x18\x06 \x01(\bR\n" +
	"Disponible\"\x83\x01\n" +
	"\x19RespuestaMetadataAudioDTO\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\x05R\x06codigo\x124\n" +
	"\bObjAudio\x18\x03 \x01(\v2\x18.servicios.MetadataAudioR\bObjAudio2a\n" +
	"\x12serviciosCanciones\x12K\n" +
	"\vbuscarAudio\x12\x16.servicios.PeticionDTO\x1a$.servicios.RespuestaMetadataAudioDTOB\x13Z\x11/serviciosCancionb\x06proto3"

var (
	file_servicios_proto_rawDescOnce sync.Once
	file_servicios_proto_rawDescData []byte
)

func file_servicios_proto_rawDescGZIP() []byte {
	file_servicios_proto_rawDescOnce.Do(func() {
		file_servicios_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicios_proto_rawDesc), len(file_servicios_proto_rawDesc)))
	})
	return file_servicios_proto_rawDescData
}

var file_servicios_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_servicios_proto_goTypes = []any{
	(*PeticionDTO)(nil),               // 0: servicios.PeticionDTO
	(*MetadataAudio)(nil),             // 1: servicios.MetadataAudio
	(*RespuestaMetadataAudioDTO)(nil), // 2: servicios.RespuestaMetadataAudioDTO
}
var file_servicios_proto_depIdxs = []int32{
	1, // 0: servicios.RespuestaMetadataAudioDTO.ObjAudio:type_name -> servicios.MetadataAudio
	0, // 1: servicios.serviciosCanciones.buscarAudio:input_type -> servicios.PeticionDTO
	2, // 2: servicios.serviciosCanciones.buscarAudio:output_type -> servicios.RespuestaMetadataAudioDTO
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_servicios_proto_init() }
func file_servicios_proto_init() {
	if File_servicios_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicios_proto_rawDesc), len(file_servicios_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicios_proto_goTypes,
		DependencyIndexes: file_servicios_proto_depIdxs,
		MessageInfos:      file_servicios_proto_msgTypes,
	}.Build()
	File_servicios_proto = out.File
	file_servicios_proto_goTypes = nil
	file_servicios_proto_depIdxs = nil
}
