// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: servicios.proto

package serviciosCancion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiciosCanciones_BuscarAudio_FullMethodName = "/servicios.serviciosCanciones/buscarAudio"
)

// ServiciosCancionesClient is the client API for ServiciosCanciones service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiciosCancionesClient interface {
	BuscarAudio(ctx context.Context, in *PeticionDTO, opts ...grpc.CallOption) (*RespuestaMetadataAudioDTO, error)
}

type serviciosCancionesClient struct {
	cc grpc.ClientConnInterface
}

func NewServiciosCancionesClient(cc grpc.ClientConnInterface) ServiciosCancionesClient {
	return &serviciosCancionesClient{cc}
}

func (c *serviciosCancionesClient) BuscarAudio(ctx context.Context, in *PeticionDTO, opts ...grpc.CallOption) (*RespuestaMetadataAudioDTO, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaMetadataAudioDTO)
	err := c.cc.Invoke(ctx, ServiciosCanciones_BuscarAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiciosCancionesServer is the server API for ServiciosCanciones service.
// All implementations must embed UnimplementedServiciosCancionesServer
// for forward compatibility.
type ServiciosCancionesServer interface {
	BuscarAudio(context.Context, *PeticionDTO) (*RespuestaMetadataAudioDTO, error)
	mustEmbedUnimplementedServiciosCancionesServer()
}

// UnimplementedServiciosCancionesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiciosCancionesServer struct{}

func (UnimplementedServiciosCancionesServer) BuscarAudio(context.Context, *PeticionDTO) (*RespuestaMetadataAudioDTO, error) {
	return nil, status.Error(codes.Unimplemented, "method BuscarAudio not implemented")
}
func (UnimplementedServiciosCancionesServer) mustEmbedUnimplementedServiciosCancionesServer() {}
func (UnimplementedServiciosCancionesServer) testEmbeddedByValue()                            {}

// UnsafeServiciosCancionesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiciosCancionesServer will
// result in compilation errors.
type UnsafeServiciosCancionesServer interface {
	mustEmbedUnimplementedServiciosCancionesServer()
}

func RegisterServiciosCancionesServer(s grpc.ServiceRegistrar, srv ServiciosCancionesServer) {
	// If the following call panics, it indicates UnimplementedServiciosCancionesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiciosCanciones_ServiceDesc, srv)
}

func _ServiciosCanciones_BuscarAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeticionDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiciosCancionesServer).BuscarAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiciosCanciones_BuscarAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiciosCancionesServer).BuscarAudio(ctx, req.(*PeticionDTO))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiciosCanciones_ServiceDesc is the grpc.ServiceDesc for ServiciosCanciones service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiciosCanciones_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicios.serviciosCanciones",
	HandlerType: (*ServiciosCancionesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "buscarAudio",
			Handler:    _ServiciosCanciones_BuscarAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servicios.proto",
}
