// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/audio_metadata.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protos_audio_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{0}
}

type AudioType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioType) Reset() {
	*x = AudioType{}
	mi := &file_protos_audio_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioType) ProtoMessage() {}

func (x *AudioType) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioType.ProtoReflect.Descriptor instead.
func (*AudioType) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *AudioType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioType) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type AudioTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioTypes    []*AudioType           `protobuf:"bytes,1,rep,name=audio_types,json=audioTypes,proto3" json:"audio_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioTypesResponse) Reset() {
	*x = AudioTypesResponse{}
	mi := &file_protos_audio_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioTypesResponse) ProtoMessage() {}

func (x *AudioTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioTypesResponse.ProtoReflect.Descriptor instead.
func (*AudioTypesResponse) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *AudioTypesResponse) GetAudioTypes() []*AudioType {
	if x != nil {
		return x.AudioTypes
	}
	return nil
}

type AudioTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioTypeId   int32                  `protobuf:"varint,1,opt,name=audio_type_id,json=audioTypeId,proto3" json:"audio_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioTypeRequest) Reset() {
	*x = AudioTypeRequest{}
	mi := &file_protos_audio_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioTypeRequest) ProtoMessage() {}

func (x *AudioTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioTypeRequest.ProtoReflect.Descriptor instead.
func (*AudioTypeRequest) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *AudioTypeRequest) GetAudioTypeId() int32 {
	if x != nil {
		return x.AudioTypeId
	}
	return 0
}

type AudiosListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audios        []*AudioSummary        `protobuf:"bytes,1,rep,name=audios,proto3" json:"audios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudiosListResponse) Reset() {
	*x = AudiosListResponse{}
	mi := &file_protos_audio_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudiosListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudiosListResponse) ProtoMessage() {}

func (x *AudiosListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudiosListResponse.ProtoReflect.Descriptor instead.
func (*AudiosListResponse) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *AudiosListResponse) GetAudios() []*AudioSummary {
	if x != nil {
		return x.Audios
	}
	return nil
}

type AudioSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioSummary) Reset() {
	*x = AudioSummary{}
	mi := &file_protos_audio_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioSummary) ProtoMessage() {}

func (x *AudioSummary) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioSummary.ProtoReflect.Descriptor instead.
func (*AudioSummary) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *AudioSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AudioSummary) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

type AudioDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDetailsRequest) Reset() {
	*x = AudioDetailsRequest{}
	mi := &file_protos_audio_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDetailsRequest) ProtoMessage() {}

func (x *AudioDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDetailsRequest.ProtoReflect.Descriptor instead.
func (*AudioDetailsRequest) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *AudioDetailsRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

type AudioDetailsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo           string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Autor            string                 `protobuf:"bytes,3,opt,name=autor,proto3" json:"autor,omitempty"`
	Album            string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	Genero           string                 `protobuf:"bytes,5,opt,name=genero,proto3" json:"genero,omitempty"`
	Duracion         int32                  `protobuf:"varint,6,opt,name=duracion,proto3" json:"duracion,omitempty"`
	TipoId           int32                  `protobuf:"varint,7,opt,name=tipo_id,json=tipoId,proto3" json:"tipo_id,omitempty"`
	TipoNombre       string                 `protobuf:"bytes,8,opt,name=tipo_nombre,json=tipoNombre,proto3" json:"tipo_nombre,omitempty"`
	FechaLanzamiento string                 `protobuf:"bytes,9,opt,name=fecha_lanzamiento,json=fechaLanzamiento,proto3" json:"fecha_lanzamiento,omitempty"`
	Disponible       bool                   `protobuf:"varint,10,opt,name=disponible,proto3" json:"disponible,omitempty"`
	NombreArchivo    string                 `protobuf:"bytes,11,opt,name=nombre_archivo,json=nombreArchivo,proto3" json:"nombre_archivo,omitempty"`
	// Música
	SelloDiscografico string `protobuf:"bytes,12,opt,name=sello_discografico,json=selloDiscografico,proto3" json:"sello_discografico,omitempty"`
	// Podcast
	NombrePodcast           string `protobuf:"bytes,13,opt,name=nombre_podcast,json=nombrePodcast,proto3" json:"nombre_podcast,omitempty"`
	NumeroTemporadaEpisodio string `protobuf:"bytes,14,opt,name=numero_temporada_episodio,json=numeroTemporadaEpisodio,proto3" json:"numero_temporada_episodio,omitempty"`
	NotasShow               string `protobuf:"bytes,15,opt,name=notas_show,json=notasShow,proto3" json:"notas_show,omitempty"`
	ClasificacionContenido  string `protobuf:"bytes,16,opt,name=clasificacion_contenido,json=clasificacionContenido,proto3" json:"clasificacion_contenido,omitempty"`
	// Audiolibro
	Narrador  string `protobuf:"bytes,17,opt,name=narrador,proto3" json:"narrador,omitempty"`
	Editorial string `protobuf:"bytes,18,opt,name=editorial,proto3" json:"editorial,omitempty"`
	Isbn      string `protobuf:"bytes,19,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Capitulo  string `protobuf:"bytes,20,opt,name=capitulo,proto3" json:"capitulo,omitempty"`
	// Ruido Blanco
	TipoSonido          string `protobuf:"bytes,21,opt,name=tipo_sonido,json=tipoSonido,proto3" json:"tipo_sonido,omitempty"`
	FuenteAudio         string `protobuf:"bytes,22,opt,name=fuente_audio,json=fuenteAudio,proto3" json:"fuente_audio,omitempty"`
	UsoSugerido         string `protobuf:"bytes,23,opt,name=uso_sugerido,json=usoSugerido,proto3" json:"uso_sugerido,omitempty"`
	ProveedorContenido  string `protobuf:"bytes,24,opt,name=proveedor_contenido,json=proveedorContenido,proto3" json:"proveedor_contenido,omitempty"`
	DuracionBucle       string `protobuf:"bytes,25,opt,name=duracion_bucle,json=duracionBucle,proto3" json:"duracion_bucle,omitempty"`
	FrecuenciaDominante string `protobuf:"bytes,26,opt,name=frecuencia_dominante,json=frecuenciaDominante,proto3" json:"frecuencia_dominante,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AudioDetailsResponse) Reset() {
	*x = AudioDetailsResponse{}
	mi := &file_protos_audio_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDetailsResponse) ProtoMessage() {}

func (x *AudioDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDetailsResponse.ProtoReflect.Descriptor instead.
func (*AudioDetailsResponse) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *AudioDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AudioDetailsResponse) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *AudioDetailsResponse) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *AudioDetailsResponse) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *AudioDetailsResponse) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

func (x *AudioDetailsResponse) GetDuracion() int32 {
	if x != nil {
		return x.Duracion
	}
	return 0
}

func (x *AudioDetailsResponse) GetTipoId() int32 {
	if x != nil {
		return x.TipoId
	}
	return 0
}

func (x *AudioDetailsResponse) GetTipoNombre() string {
	if x != nil {
		return x.TipoNombre
	}
	return ""
}

func (x *AudioDetailsResponse) GetFechaLanzamiento() string {
	if x != nil {
		return x.FechaLanzamiento
	}
	return ""
}

func (x *AudioDetailsResponse) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

func (x *AudioDetailsResponse) GetNombreArchivo() string {
	if x != nil {
		return x.NombreArchivo
	}
	return ""
}

func (x *AudioDetailsResponse) GetSelloDiscografico() string {
	if x != nil {
		return x.SelloDiscografico
	}
	return ""
}

func (x *AudioDetailsResponse) GetNombrePodcast() string {
	if x != nil {
		return x.NombrePodcast
	}
	return ""
}

func (x *AudioDetailsResponse) GetNumeroTemporadaEpisodio() string {
	if x != nil {
		return x.NumeroTemporadaEpisodio
	}
	return ""
}

func (x *AudioDetailsResponse) GetNotasShow() string {
	if x != nil {
		return x.NotasShow
	}
	return ""
}

func (x *AudioDetailsResponse) GetClasificacionContenido() string {
	if x != nil {
		return x.ClasificacionContenido
	}
	return ""
}

func (x *AudioDetailsResponse) GetNarrador() string {
	if x != nil {
		return x.Narrador
	}
	return ""
}

func (x *AudioDetailsResponse) GetEditorial() string {
	if x != nil {
		return x.Editorial
	}
	return ""
}

func (x *AudioDetailsResponse) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *AudioDetailsResponse) GetCapitulo() string {
	if x != nil {
		return x.Capitulo
	}
	return ""
}

func (x *AudioDetailsResponse) GetTipoSonido() string {
	if x != nil {
		return x.TipoSonido
	}
	return ""
}

func (x *AudioDetailsResponse) GetFuenteAudio() string {
	if x != nil {
		return x.FuenteAudio
	}
	return ""
}

func (x *AudioDetailsResponse) GetUsoSugerido() string {
	if x != nil {
		return x.UsoSugerido
	}
	return ""
}

func (x *AudioDetailsResponse) GetProveedorContenido() string {
	if x != nil {
		return x.ProveedorContenido
	}
	return ""
}

func (x *AudioDetailsResponse) GetDuracionBucle() string {
	if x != nil {
		return x.DuracionBucle
	}
	return ""
}

func (x *AudioDetailsResponse) GetFrecuenciaDominante() string {
	if x != nil {
		return x.FrecuenciaDominante
	}
	return ""
}

type AudioFilenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFilenameRequest) Reset() {
	*x = AudioFilenameRequest{}
	mi := &file_protos_audio_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFilenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFilenameRequest) ProtoMessage() {}

func (x *AudioFilenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFilenameRequest.ProtoReflect.Descriptor instead.
func (*AudioFilenameRequest) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{8}
}

func (x *AudioFilenameRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

type AudioFilenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFilenameResponse) Reset() {
	*x = AudioFilenameResponse{}
	mi := &file_protos_audio_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFilenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFilenameResponse) ProtoMessage() {}

func (x *AudioFilenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFilenameResponse.ProtoReflect.Descriptor instead.
func (*AudioFilenameResponse) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *AudioFilenameResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type PeticionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionDTO) Reset() {
	*x = PeticionDTO{}
	mi := &file_protos_audio_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionDTO) ProtoMessage() {}

func (x *PeticionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionDTO.ProtoReflect.Descriptor instead.
func (*PeticionDTO) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *PeticionDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

type MetadataAudio struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Titulo                  string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Autor                   string                 `protobuf:"bytes,2,opt,name=autor,proto3" json:"autor,omitempty"`
	Album                   string                 `protobuf:"bytes,3,opt,name=album,proto3" json:"album,omitempty"`
	Genero                  string                 `protobuf:"bytes,4,opt,name=genero,proto3" json:"genero,omitempty"`
	Duracion                int32                  `protobuf:"varint,5,opt,name=duracion,proto3" json:"duracion,omitempty"`
	TipoId                  int32                  `protobuf:"varint,6,opt,name=tipo_id,json=tipoId,proto3" json:"tipo_id,omitempty"`
	TipoNombre              string                 `protobuf:"bytes,7,opt,name=tipo_nombre,json=tipoNombre,proto3" json:"tipo_nombre,omitempty"`
	FechaLanzamiento        string                 `protobuf:"bytes,8,opt,name=fecha_lanzamiento,json=fechaLanzamiento,proto3" json:"fecha_lanzamiento,omitempty"`
	Disponible              bool                   `protobuf:"varint,9,opt,name=disponible,proto3" json:"disponible,omitempty"`
	NombreArchivo           string                 `protobuf:"bytes,10,opt,name=nombre_archivo,json=nombreArchivo,proto3" json:"nombre_archivo,omitempty"`
	SelloDiscografico       string                 `protobuf:"bytes,11,opt,name=sello_discografico,json=selloDiscografico,proto3" json:"sello_discografico,omitempty"`
	NombrePodcast           string                 `protobuf:"bytes,12,opt,name=nombre_podcast,json=nombrePodcast,proto3" json:"nombre_podcast,omitempty"`
	NumeroTemporadaEpisodio string                 `protobuf:"bytes,13,opt,name=numero_temporada_episodio,json=numeroTemporadaEpisodio,proto3" json:"numero_temporada_episodio,omitempty"`
	NotasShow               string                 `protobuf:"bytes,14,opt,name=notas_show,json=notasShow,proto3" json:"notas_show,omitempty"`
	ClasificacionContenido  string                 `protobuf:"bytes,15,opt,name=clasificacion_contenido,json=clasificacionContenido,proto3" json:"clasificacion_contenido,omitempty"`
	Narrador                string                 `protobuf:"bytes,16,opt,name=narrador,proto3" json:"narrador,omitempty"`
	Editorial               string                 `protobuf:"bytes,17,opt,name=editorial,proto3" json:"editorial,omitempty"`
	Isbn                    string                 `protobuf:"bytes,18,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Capitulo                string                 `protobuf:"bytes,19,opt,name=capitulo,proto3" json:"capitulo,omitempty"`
	TipoSonido              string                 `protobuf:"bytes,20,opt,name=tipo_sonido,json=tipoSonido,proto3" json:"tipo_sonido,omitempty"`
	FuenteAudio             string                 `protobuf:"bytes,21,opt,name=fuente_audio,json=fuenteAudio,proto3" json:"fuente_audio,omitempty"`
	UsoSugerido             string                 `protobuf:"bytes,22,opt,name=uso_sugerido,json=usoSugerido,proto3" json:"uso_sugerido,omitempty"`
	ProveedorContenido      string                 `protobuf:"bytes,23,opt,name=proveedor_contenido,json=proveedorContenido,proto3" json:"proveedor_contenido,omitempty"`
	DuracionBucle           string                 `protobuf:"bytes,24,opt,name=duracion_bucle,json=duracionBucle,proto3" json:"duracion_bucle,omitempty"`
	FrecuenciaDominante     string                 `protobuf:"bytes,25,opt,name=frecuencia_dominante,json=frecuenciaDominante,proto3" json:"frecuencia_dominante,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MetadataAudio) Reset() {
	*x = MetadataAudio{}
	mi := &file_protos_audio_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataAudio) ProtoMessage() {}

func (x *MetadataAudio) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataAudio.ProtoReflect.Descriptor instead.
func (*MetadataAudio) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *MetadataAudio) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *MetadataAudio) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *MetadataAudio) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *MetadataAudio) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

func (x *MetadataAudio) GetDuracion() int32 {
	if x != nil {
		return x.Duracion
	}
	return 0
}

func (x *MetadataAudio) GetTipoId() int32 {
	if x != nil {
		return x.TipoId
	}
	return 0
}

func (x *MetadataAudio) GetTipoNombre() string {
	if x != nil {
		return x.TipoNombre
	}
	return ""
}

func (x *MetadataAudio) GetFechaLanzamiento() string {
	if x != nil {
		return x.FechaLanzamiento
	}
	return ""
}

func (x *MetadataAudio) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

func (x *MetadataAudio) GetNombreArchivo() string {
	if x != nil {
		return x.NombreArchivo
	}
	return ""
}

func (x *MetadataAudio) GetSelloDiscografico() string {
	if x != nil {
		return x.SelloDiscografico
	}
	return ""
}

func (x *MetadataAudio) GetNombrePodcast() string {
	if x != nil {
		return x.NombrePodcast
	}
	return ""
}

func (x *MetadataAudio) GetNumeroTemporadaEpisodio() string {
	if x != nil {
		return x.NumeroTemporadaEpisodio
	}
	return ""
}

func (x *MetadataAudio) GetNotasShow() string {
	if x != nil {
		return x.NotasShow
	}
	return ""
}

func (x *MetadataAudio) GetClasificacionContenido() string {
	if x != nil {
		return x.ClasificacionContenido
	}
	return ""
}

func (x *MetadataAudio) GetNarrador() string {
	if x != nil {
		return x.Narrador
	}
	return ""
}

func (x *MetadataAudio) GetEditorial() string {
	if x != nil {
		return x.Editorial
	}
	return ""
}

func (x *MetadataAudio) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *MetadataAudio) GetCapitulo() string {
	if x != nil {
		return x.Capitulo
	}
	return ""
}

func (x *MetadataAudio) GetTipoSonido() string {
	if x != nil {
		return x.TipoSonido
	}
	return ""
}

func (x *MetadataAudio) GetFuenteAudio() string {
	if x != nil {
		return x.FuenteAudio
	}
	return ""
}

func (x *MetadataAudio) GetUsoSugerido() string {
	if x != nil {
		return x.UsoSugerido
	}
	return ""
}

func (x *MetadataAudio) GetProveedorContenido() string {
	if x != nil {
		return x.ProveedorContenido
	}
	return ""
}

func (x *MetadataAudio) GetDuracionBucle() string {
	if x != nil {
		return x.DuracionBucle
	}
	return ""
}

func (x *MetadataAudio) GetFrecuenciaDominante() string {
	if x != nil {
		return x.FrecuenciaDominante
	}
	return ""
}

type RespuestaMetadataAudioDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjAudio      *MetadataAudio         `protobuf:"bytes,1,opt,name=obj_audio,json=objAudio,proto3" json:"obj_audio,omitempty"`
	Codigo        int32                  `protobuf:"varint,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Mensaje       string                 `protobuf:"bytes,3,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaMetadataAudioDTO) Reset() {
	*x = RespuestaMetadataAudioDTO{}
	mi := &file_protos_audio_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaMetadataAudioDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaMetadataAudioDTO) ProtoMessage() {}

func (x *RespuestaMetadataAudioDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_audio_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaMetadataAudioDTO.ProtoReflect.Descriptor instead.
func (*RespuestaMetadataAudioDTO) Descriptor() ([]byte, []int) {
	return file_protos_audio_metadata_proto_rawDescGZIP(), []int{12}
}

func (x *RespuestaMetadataAudioDTO) GetObjAudio() *MetadataAudio {
	if x != nil {
		return x.ObjAudio
	}
	return nil
}

func (x *RespuestaMetadataAudioDTO) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *RespuestaMetadataAudioDTO) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_protos_audio_metadata_proto protoreflect.FileDescriptor

const file_protos_audio_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1bprotos/audio_metadata.proto\x12\tservicios\"\a\n" +
	"\x05Empty\"3\n" +
	"\tAudioType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\"K\n" +
	"\x12AudioTypesResponse\x125\n" +
	"\vaudio_types\x18\x01 \x03(\v2\x14.servicios.AudioTypeR\n" +
	"audioTypes\"6\n" +
	"\x10AudioTypeRequest\x12\"\n" +
	"\raudio_type_id\x18\x01 \x01(\x05R\vaudioTypeId\"E\n" +
	"\x12AudiosListResponse\x12/\n" +
	"\x06audios\x18\x01 \x03(\v2\x17.servicios.AudioSummaryR\x06audios\"6\n" +
	"\fAudioSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\"0\n" +
	"\x13AudioDetailsRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\"\x92\a\n" +
	"\x14AudioDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x14\n" +
	"\x05autor\x18\x03 \x01(\tR\x05autor\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x16\n" +
	"\x06genero\x18\x05 \x01(\tR\x06genero\x12\x1a\n" +
	"\bduracion\x18\x06 \x01(\x05R\bduracion\x12\x17\n" +
	"\atipo_id\x18\a \x01(\x05R\x06tipoId\x12\x1f\n" +
	"\vtipo_nombre\x18\b \x01(\tR\n" +
	"tipoNombre\x12+\n" +
	"\x11fecha_lanzamiento\x18\t \x01(\tR\x10fechaLanzamiento\x12\x1e\n" +
	"\n" +
	"disponible\x18\n" +
	" \x01(\bR\n" +
	"disponible\x12%\n" +
	"\x0enombre_archivo\x18\v \x01(\tR\rnombreArchivo\x12-\n" +
	"\x12sello_discografico\x18\f \x01(\tR\x11selloDiscografico\x12%\n" +
	"\x0enombre_podcast\x18\r \x01(\tR\rnombrePodcast\x12:\n" +
	"\x19numero_temporada_episodio\x18\x0e \x01(\tR\x17numeroTemporadaEpisodio\x12\x1d\n" +
	"\n" +
	"notas_show\x18\x0f \x01(\tR\tnotasShow\x127\n" +
	"\x17clasificacion_contenido\x18\x10 \x01(\tR\x16clasificacionContenido\x12\x1a\n" +
	"\bnarrador\x18\x11 \x01(\tR\bnarrador\x12\x1c\n" +
	"\teditorial\x18\x12 \x01(\tR\teditorial\x12\x12\n" +
	"\x04isbn\x18\x13 \x01(\tR\x04isbn\x12\x1a\n" +
	"\bcapitulo\x18\x14 \x01(\tR\bcapitulo\x12\x1f\n" +
	"\vtipo_sonido\x18\x15 \x01(\tR\n" +
	"tipoSonido\x12!\n" +
	"\ffuente_audio\x18\x16 \x01(\tR\vfuenteAudio\x12!\n" +
	"\fuso_sugerido\x18\x17 \x01(\tR\vusoSugerido\x12/\n" +
	"\x13proveedor_contenido\x18\x18 \x01(\tR\x12proveedorContenido\x12%\n" +
	"\x0eduracion_bucle\x18\x19 \x01(\tR\rduracionBucle\x121\n" +
	"\x14frecuencia_dominante\x18\x1a \x01(\tR\x13frecuenciaDominante\"1\n" +
	"\x14AudioFilenameRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\"3\n" +
	"\x15AudioFilenameResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"%\n" +
	"\vPeticionDTO\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\"\xfb\x06\n" +
	"\rMetadataAudio\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\x12\x14\n" +
	"\x05autor\x18\x02 \x01(\tR\x05autor\x12\x14\n" +
	"\x05album\x18\x03 \x01(\tR\x05album\x12\x16\n" +
	"\x06genero\x18\x04 \x01(\tR\x06genero\x12\x1a\n" +
	"\bduracion\x18\x05 \x01(\x05R\bduracion\x12\x17\n" +
	"\atipo_id\x18\x06 \x01(\x05R\x06tipoId\x12\x1f\n" +
	"\vtipo_nombre\x18\a \x01(\tR\n" +
	"tipoNombre\x12+\n" +
	"\x11fecha_lanzamiento\x18\b \x01(\tR\x10fechaLanzamiento\x12\x1e\n" +
	"\n" +
	"disponible\x18\t \x01(\bR\n" +
	"disponible\x12%\n" +
	"\x0enombre_archivo\x18\n" +
	" \x01(\tR\rnombreArchivo\x12-\n" +
	"\x12sello_discografico\x18\v \x01(\tR\x11selloDiscografico\x12%\n" +
	"\x0enombre_podcast\x18\f \x01(\tR\rnombrePodcast\x12:\n" +
	"\x19numero_temporada_episodio\x18\r \x01(\tR\x17numeroTemporadaEpisodio\x12\x1d\n" +
	"\n" +
	"notas_show\x18\x0e \x01(\tR\tnotasShow\x127\n" +
	"\x17clasificacion_contenido\x18\x0f \x01(\tR\x16clasificacionContenido\x12\x1a\n" +
	"\bnarrador\x18\x10 \x01(\tR\bnarrador\x12\x1c\n" +
	"\teditorial\x18\x11 \x01(\tR\teditorial\x12\x12\n" +
	"\x04isbn\x18\x12 \x01(\tR\x04isbn\x12\x1a\n" +
	"\bcapitulo\x18\x13 \x01(\tR\bcapitulo\x12\x1f\n" +
	"\vtipo_sonido\x18\x14 \x01(\tR\n" +
	"tipoSonido\x12!\n" +
	"\ffuente_audio\x18\x15 \x01(\tR\vfuenteAudio\x12!\n" +
	"\fuso_sugerido\x18\x16 \x01(\tR\vusoSugerido\x12/\n" +
	"\x13proveedor_contenido\x18\x17 \x01(\tR\x12proveedorContenido\x12%\n" +
	"\x0eduracion_bucle\x18\x18 \x01(\tR\rduracionBucle\x121\n" +
	"\x14frecuencia_dominante\x18\x19 \x01(\tR\x13frecuenciaDominante\"\x84\x01\n" +
	"\x19RespuestaMetadataAudioDTO\x125\n" +
	"\tobj_audio\x18\x01 \x01(\v2\x18.servicios.MetadataAudioR\bobjAudio\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\x05R\x06codigo\x12\x18\n" +
	"\amensaje\x18\x03 \x01(\tR\amensaje2\x9a\x03\n" +
	"\x0fMetadataService\x12@\n" +
	"\rGetAudioTypes\x12\x10.servicios.Empty\x1a\x1d.servicios.AudioTypesResponse\x12M\n" +
	"\x0fGetAudiosByType\x12\x1b.servicios.AudioTypeRequest\x1a\x1d.servicios.AudiosListResponse\x12R\n" +
	"\x0fGetAudioDetails\x12\x1e.servicios.AudioDetailsRequest\x1a\x1f.servicios.AudioDetailsResponse\x12U\n" +
	"\x10GetAudioFilename\x12\x1f.servicios.AudioFilenameRequest\x1a .servicios.AudioFilenameResponse\x12K\n" +
	"\vBuscarAudio\x12\x16.servicios.PeticionDTO\x1a$.servicios.RespuestaMetadataAudioDTOB\tZ\a/protosb\x06proto3"

var (
	file_protos_audio_metadata_proto_rawDescOnce sync.Once
	file_protos_audio_metadata_proto_rawDescData []byte
)

func file_protos_audio_metadata_proto_rawDescGZIP() []byte {
	file_protos_audio_metadata_proto_rawDescOnce.Do(func() {
		file_protos_audio_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_audio_metadata_proto_rawDesc), len(file_protos_audio_metadata_proto_rawDesc)))
	})
	return file_protos_audio_metadata_proto_rawDescData
}

var file_protos_audio_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_audio_metadata_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: servicios.Empty
	(*AudioType)(nil),                 // 1: servicios.AudioType
	(*AudioTypesResponse)(nil),        // 2: servicios.AudioTypesResponse
	(*AudioTypeRequest)(nil),          // 3: servicios.AudioTypeRequest
	(*AudiosListResponse)(nil),        // 4: servicios.AudiosListResponse
	(*AudioSummary)(nil),              // 5: servicios.AudioSummary
	(*AudioDetailsRequest)(nil),       // 6: servicios.AudioDetailsRequest
	(*AudioDetailsResponse)(nil),      // 7: servicios.AudioDetailsResponse
	(*AudioFilenameRequest)(nil),      // 8: servicios.AudioFilenameRequest
	(*AudioFilenameResponse)(nil),     // 9: servicios.AudioFilenameResponse
	(*PeticionDTO)(nil),               // 10: servicios.PeticionDTO
	(*MetadataAudio)(nil),             // 11: servicios.MetadataAudio
	(*RespuestaMetadataAudioDTO)(nil), // 12: servicios.RespuestaMetadataAudioDTO
}
var file_protos_audio_metadata_proto_depIdxs = []int32{
	1,  // 0: servicios.AudioTypesResponse.audio_types:type_name -> servicios.AudioType
	5,  // 1: servicios.AudiosListResponse.audios:type_name -> servicios.AudioSummary
	11, // 2: servicios.RespuestaMetadataAudioDTO.obj_audio:type_name -> servicios.MetadataAudio
	0,  // 3: servicios.MetadataService.GetAudioTypes:input_type -> servicios.Empty
	3,  // 4: servicios.MetadataService.GetAudiosByType:input_type -> servicios.AudioTypeRequest
	6,  // 5: servicios.MetadataService.GetAudioDetails:input_type -> servicios.AudioDetailsRequest
	8,  // 6: servicios.MetadataService.GetAudioFilename:input_type -> servicios.AudioFilenameRequest
	10, // 7: servicios.MetadataService.BuscarAudio:input_type -> servicios.PeticionDTO
	2,  // 8: servicios.MetadataService.GetAudioTypes:output_type -> servicios.AudioTypesResponse
	4,  // 9: servicios.MetadataService.GetAudiosByType:output_type -> servicios.AudiosListResponse
	7,  // 10: servicios.MetadataService.GetAudioDetails:output_type -> servicios.AudioDetailsResponse
	9,  // 11: servicios.MetadataService.GetAudioFilename:output_type -> servicios.AudioFilenameResponse
	12, // 12: servicios.MetadataService.BuscarAudio:output_type -> servicios.RespuestaMetadataAudioDTO
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_protos_audio_metadata_proto_init() }
func file_protos_audio_metadata_proto_init() {
	if File_protos_audio_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_audio_metadata_proto_rawDesc), len(file_protos_audio_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_audio_metadata_proto_goTypes,
		DependencyIndexes: file_protos_audio_metadata_proto_depIdxs,
		MessageInfos:      file_protos_audio_metadata_proto_msgTypes,
	}.Build()
	File_protos_audio_metadata_proto = out.File
	file_protos_audio_metadata_proto_goTypes = nil
	file_protos_audio_metadata_proto_depIdxs = nil
}
